export Layout from '../layout';
export Home from './home';
export Login from './login';
export Register from './register';
export Article from './article';
export Setting from './setting';
export Collect from './collect'
export User from './user'
export Member from './member'
export Achievement from './achievement'
export Resource from './resource'
