module.exports={
    apply:'/back/user/apply',//申请列表
    all:'/back/user/all',//全员信息，
    userInfo:'/back/user/info',//查询该成员的所有详细信息
    article:'/',
    achievement:'',
    login:'',
    userDelete:'/back/user/softDeleteOne',
    userAgree:"/back/user/agreeOne",
    userInfo:'/back/user/info'
}
